local list = {
[[What’s *your* problem?]],
[[Will you stop that constant whining? What makes you think that anyone cares?]],
[[Have you gotten tired yet of all this me-me-me stuff?]],
[[You just need to give yourself a kick in the rear.]],
[[But it’s all in your mind.]],
[[I thought you were stronger than that.]],
[[No one ever said life was fair.]],
[[As you get stronger you won’t have to wallow in it as much.]],
[[Pull yourself up by your bootstraps.]],
[[Do you feel better now? (Usually said following a five minute conversation in which the speaker has asked me “what’s wrong?” and “would you like to talk about it?” with the best of intentions, but absolutely no under-standing of depression as anything but an irrational sadness.)]],
[[Why don’t you just grow up?]],
[[Stop feeling sorry for yourself.]],
[[There are a lot of people worse off than you?]],
[[You have it so good, why aren’t you happy?]],
[[It’s a beautiful day!]],
[[You have so many things to be thankful for, why are you depressed!]],
[[What do you have to be depressed about.]],
[[Happiness is a choice]],
[[You think *you’ve* got problems…]],
[[Well at least it’s not that bad.]],
[[Maybe you should take vitamins for your stress.]],
[[There is always somebody worse off than you are.]],
[[Lighten up!]],
[[You should get off all those pills.]],
[[You are what you think.]],
[[Cheer up!]],
[[You’re always feeling sorry for yourself.]],
[[Why can’t you just be normal?]],
[[Things aren’t *that* bad, are they?]],
[[Have you been praying/reading the Bible?]],
[[You need to get out more.]],
[[We have to get together some time. (Yeah, right!)]],
[[Get a grip!]],
[[Most folks are about as happy as they make up their minds to be.]],
[[Take a hot bath. That’s what I always do when I’m upset.]],
[[Well, everyone gets depressed sometimes!]],
[[Get a job!]],
[[Smile and the world smiles with you, cry and you cry alone.]],
[[You don’t *look* depressed!]],
[[You’re so selfish!]],
[[You never think of anyone but yourself.]],
[[You’re just looking for attention.]],
[[Have you got PMS?]],
[[You’ll be a better person because of it!]],
[[Everybody has a bad day now and then.]],
[[You should buy nicer clothes to wear.]],
[[You catch more flies with honey than with vinegar.]],
[[Why don’t you smile more?]],
[[A person your age should be having the time of your life.]],
[[The only one you’re hurting is yourself.]],
[[You can do anything you want if you just set your mind to it.]],
[[This is a place of BUSINESS, not a HOSPITAL; after confiding to supervisor about my depression]],
[[Depression is a symptom of your sin against God.]],
[[You brought it on yourself]],
[[You can make the choice for depression and its effects, or against depression, it’s all in YOUR hands.]],
[[Get off your rear and do something. -or- Just do it!]],
[[Why should I care?]],
[[Snap out of it, will you?]],
[[You *want* to feel this way.]],
[[You have no reason to feel this way.]],
[[Its your own fault.]],
[[That which does not kill us makes us stronger.]],
[[You’re always worried about *your* problems.]],
[[Your problems aren’t that big.]],
[[What are you worried about? You should be fine.]],
[[Just don’t think about it.]],
[[Go Away.]],
[[You don’t have the ability to do it.]],
[[Just wait a few weeks, it’ll be over soon.]],
[[Go out and have some fun!]],
[[You’re making me depressed as well…]],
[[I just want to help you.]],
[[The world out there is not that bad…]],
[[Just try a little harder!]],
[[Believe me, I know how you feel. I was depressed once for several days.]],
[[You need a boy/girl-friend.]],
[[You need a hobby.]],
[[Just pull yourself together]],
[[You’d feel better if you went to church]],
[[I think your depression is a way of punishing us. —My mother]],
[[Sh*t or get off the pot.]],
[[So, you’re depressed. Aren’t you always?]],
[[What you need is some real tragedy in your life to give you perspective.]],
[[You’re a writer, aren’t you? Just think of all the good material you’re getting out of this.]],
[[This one is best executed with an evangelical-style handshake, i.e. one of my hands is imprisoned by two belonging to a beefy person who thinks he has a lot more charisma than I do: “Our thoughts and prayers are with you.” This has actually happened to me. Bitten-back response: Who are ‘our’? And don’t do me any favors, schmuck.]],
[[Have you tried camomile tea?]],
[[So, you’re depressed. Aren’t you always?]],
[[You will be ok, just hang in there, it will pass. This too shall pass. – Ann Landers]],
[[Oh, perk up!]],
[[Try not being so depressed.]],
[[Quit whining. Go out and help people and you won’t have time to brood…]],
[[Go out and get some fresh air… that always makes me feel better.]],
[[You have to take up your bed and carry on.]],
[[Why don’t you give up going to these quacks (ie doctors) and throw out those pills, then you’ll feel better.]],
[[Well, we all have our cross to bear.]],
[[You should join band or chorus or something. That way you won’t be thinking about yourself so much.]],
[[You change your mind.]],
[[You’re useless.]],
[[Nobody is responsible for your depression.]],
[[You don’t like feeling that way? So, change it.]],
}
return list[math.random(#list)]
