local list = {
"It's kinda sad watching you attempt to fit your entire vocabulary into a sentence.",
"If assholes could fly, this place would be an airport!",
"You are proof that God has a sense of humor.",
"It's better to let someone think you are an Idiot than to open your mouth and prove it.",
"Shut up, you'll never be the man your mother is.",
"Do you wanna lose ten pounds of ugly fat? Cut off your head",
"Well I could agree with you, but then we'd both be wrong.",
"Roses are red violets are blue, God made me pretty, what happened to you?",
"Do you still love nature, despite what it did to you?",
"Am I getting smart with you? How would you know?",
"If I were to slap you, it would be considered animal abuse!",
"Did your parents keep the placenta and throw away the baby?",
"Why don't you slip into something more comfortable -- like a coma.",
"So, a thought crossed your mind? Must have been a long and lonely journey. ",
"Shock me, say something intelligent.",
"I've seen people like you, but I had to pay admission!",
"You look like a before picture.",
"Ordinarily people live and learn. You just live.",
"What are you doing here? Did someone leave your cage open?",
"I love what you've done with your hair. How do you get it to come out of the nostrils like that?",
"Everyone who ever loved you was wrong.",
"Maybe if you ate some of that makeup you could be pretty on the inside.",
"Learn from your parents' mistakes - use birth control!",
"You stare at frozen juice cans because they say, \"concentrate\".",
"Don't you need a license to be that ugly?",
"Nice tan, orange is my favorite color.",
"You so ugly when who were born the doctor threw you out the window and the window threw you back!",
"You couldn't pour water out of a boot if the instructions were on the heel.",
"If you spoke your mind, you'd be speechless.",
"Are you always an idiot, or just when I'm around?",
"If a crackhead saw you, he'd think he needs to go on a diet.",
"You are so stupid, you'd trip over a cordless phone.",
"Looks like you traded in your neck for an extra chin!",
"You are proof that evolution CAN go in reverse.",
"You may not be the best looking girl here, but beauty is only a light switch away!",
"So you've changed your mind, does this one work any better?",
"Your parents hated you so much you bath toys were an iron and a toaster",
"I'll never forget the first time we met, although I'll keep trying.",
"You act like your arrogance is a virtue.",
"If what you don't know can't hurt you, you're invulnerable.",
"Your ambition outweighs your relevant skills.",
"It’s better to keep your mouth shut and give the 'impression' that you’re stupid than to open it and remove all doubt.",
"I may be fat, but you're ugly, and I can lose weight.",
"I heard you took an IQ test and they said you're results were negative.",
"Aww, it's so cute when you try to talk about things you don't understand.",
"You are so old, your birth-certificate expired.",
"Don't feel sad, don't feel blue, Frankenstein was ugly too.",
"100,000 sperm, you were the fastest?",
"You do realize makeup isn't going to fix your stupidity?",
"We all sprang from apes, but you didn't spring far enough.",
"Jesus loves you, everyone else thinks you're an asshole!",
"You occasionally stumble over the truth, but you quickly pick yourself up and carry on as if nothing happened.",
"I'd like to help you out. Which way did you come in? ",
"If you had another brain, it would be lonely.",
"You must think you're strong, but you only smell strong.",
"Oh my God, look at you. Was anyone else hurt in the accident?",
"Your dad's condom is a bigger than your personality.",
"You're so stupid, it takes you an hour to cook minute rice.",
"It’s too bad stupidity isn’t painful.",
"You are so old, you fart dust.",
"Come again when you can't stay quite so long.",
"Being around you is like having a cancer of the soul.",
"I don't know what makes you so stupid, but it really works!",
"You're as useless as a screen door on a submarine.",
"You're as useful as an ashtray on a motorcycle.",
"The best part of you is still running down your old mans leg.",
"Brains aren't everything. In your case they're nothing.",
"If your brain exploded, it wouldn't even mess up your hair.",
"If I want your opinion, I'll give it to you.",
"You couldn't hit water if you fell out of a boat.",
"Are your parents siblings?",
"If brains were dynamite you wouldn't have enough to blow your nose.",
"When was the last time you could see your whole body in the mirror?",
"You're the reason why women earn 75 cents to the dollar.",
"I look into your eyes and get the feeling someone else is driving.",
"If you are going to be two faced, at least make one of them pretty.",
"You'll make a great first wife some day.",
"Yeah you're pretty, pretty stupid",
"Ever since I saw you in your family tree, I've wanted to cut it down.",
"Is your name Maple Syrup? It should be, you sap.",
"Even if you were twice as smart, you'd still be stupid!",
"You are depriving some poor village of its idiot.",
"You must have a very low opinion of people if you think they are your equals.",
"For those who never forget a face, you are an exception.",
"I thought of you all day today. I was at the zoo.",
"You are so old, even your memory is in black and white.",
"Beauty is skin deep, but ugly is to the bone.",
"I hear the only place you're ever invited is outside.",
"Just reminding u there is a very fine line between hobby and mental illness.",
"People like you are the reason I work out.",
"Your mom must have a really loud bark!",
"I wish you no harm, but it would have been much better if you had never lived.",
"When anorexics see you, they think they need to go on a diet.",
"Please tell me you don't home-school your kids.",
"You're stupid because you're blonde.",
}
return pickone(list)
