
local array = {
[[Gb Gur Negvfg Bs Guvf Pbzvat Trarengvba Naq Bs Gur Eranvffnapr. Gur Crbcyr Gung Gehyl Haqrefgnaq Lbhe Neg ner Gur Crbcyr Jub Qba'g Pbzzrag]],
[[Nyy Gur Ehyrf Va Guvf Jbeyq Jrer Znqr Ol Fbzrbar Ab Fznegre Guna Lbh. Fb Znxr Lbhe Bja]],
[[Nalbar Obea Ba Guvf Cynarg Fubhyq Unir N Cynargnel Pvgvmrafuvc Ranoyvat Gurz Gb Serryl Rkcyber Gurer Ubzr]],
[[Qba'g Jnag Lbh Thlf Gb Guvax Orpnhfr V Jnf Obea Va Nzrevpn Gung V Fcrnx Naq Novqr Ol Ratyvfu Tenzzne. V Fcrnx Wnqra, Vaqrsvavgryl.]],
[[Qlvat Vf ZnvaFgernz #ZBARL]],
[[Rvgure V Yvr Gb Lbh Be Jr Pel Gbtrgure]],
[[Rirel 7 Lrnef Lbhe Obql Vf Pbzcyrgryl Ercynprq Jvgu Ragveryl Arj Pryyf Fb Whfg Orpnhfr Lbh Ybbx Gur Fnzr Qbrfa'g Zrna Lbh Ner.]],
[[Terra Juvgr Naq Oyhr Znxr Qernzf Pbzr Gehr.]],
[[Ubj Pna Zveebef Or Erny Vs Bhe Rlrf Nera'g Erny]],
[[V Ohvyq Clenzvqf Pbafgnagyl]],
[[V Rapbhentr Lbh Nyy Gb Hasbyybj Zr Fb V Pna Or Yrsg Jvgu Gur Crbcyr Jub Npghnyyl Nccerpvngr Cuvybfbcul Naq Cbrgel. / #PbbyGncrIby2]],
[[Vs N Obbx Fgber Arire Ehaf Bhg Bs N Pregnva Obbx, Qbfr Gung Zrna Gung Abobql Ernqf Vg, Be Rirelobql Ernqf Vg]],
[[Vs Rirelobql Va Gur Jbeyq Qebccrq Bhg Bs Fpubby Jr Jbhyq Unir N Zhpu Zber Vagryyvtrag Fbpvrgl]],
[[Vs V Qvr Va Zl Synaary Jvyy Lbh Jevgr Zl Cbrzf Ba Glyre'f 5 Cnaryf Naq Wrfhfhf Fnaqnyf Guvf Cynar Vf Whfg Gb Zhpu Gb Unaqyr.]],
[[Vs Arjobea Onovrf Pbhyq Fcrnx Gurl Jbhyq Or Gur Zbfg Vagryyvtrag Orvatf Ba Cynarg Rnegu]],
[[V Ubcr Vg Qbrfa'g Gnxr Sbe Zr Gb Qvr Sbe Lbh Gb Frr Jung V Qb Sbe Lbh]],
[[V Bayl Nccyl Gb Gur Fvkgu Nzraqzrag]],
[[V Fpner Crbcyr Njnl]],
[[V Fubhyq Whfg Fgbc Gjrrgvat, Gur Uhzna Pbafpvbhfarff Zhfg Envfr Orsber V Fcrnx Zl Whiravyr Cuvybfbcul. / Fubhgf Bhg Gb @GVZR]],
[["Vg'f Lbhe Oveguqnl" Zngrb Fnvq. V Qvqa'g Erfcbaq. "Ner Lbh Abg Rkpvgrq Gb Or 15" Ur Nfxrq. Ernqvat Zl Obbx V Hggrerq "V Ghearq 15 Ybat Ntb"]],
[[V'ir Ova Qevaxvat Qvfgvyyrq Jngre Sbe Fb Ybat Gung Jura V Qevax Abezny Jngre Vg Srryf Yvxr V'z Fjnyybjvat Uhtr Puhaxf Bs Nyhzvahz.]],
[[V Jngpu Gjvyvtug Rirel Avtug]],
[[Yngryl Crbcyr Pnyy Zr Fpbbc Yvsr]],
[[Zbfg Gerrf Ner Oyhr]],
[[Bapr Lbh Tb Va Lbh Nyjnlf Pbzr Bhg Nyvir]],
[[Crbcyr Gryy Zr Gb Fzvyr V Gryy Gurz Gur Ynpx Bs Rzbgvba Va Zl Snpr Qbrfa'g Zrna V'z Haunccl]],
[[Crbcyr Guvax N EryngvbaFuvc Znxrf Lbh Jubyr, Gung Vg'f Gjb 50%'f Pbzvat Gbtrgure Gb Znxr 100% Jura Vg Fubhyq Or Gjb 100%'f Znxvat 200%•••]],
[[Crbcyr Hfr Gb Nfx Zr Jung Qb Lbh Jnaan Or Jura Lbh Trg Byqre Naq V Jbhyq Fnl Jung N Fghcvq Dhrfgvba Gur Erny Dhrfgvba Vf Jung Nz V Evtug Abj]],
[[Fpubby Vf Gur Gbby Gb Oenvajnfu Gur Lbhgu]],
[[Fgbc Tbffvcvat Ersyrpg Vagreanyyl Lbh Jvyy Svaq Lbhefrys N Artyrpgrq Cneg Bs Lbhe Frys.]],
[[Gurer Vf Ab Ahgevragf Va Bhe Sbbq Nalzber Be Va Bhe Fbvy BE VA BHE JNGRE]],
[[Gerrf Ner Arire Fnq Ybbx Ng Gurz Rirel Bapr Va Njuvyr Gurl'er Dhvgr Ornhgvshy]],
[[Hanjnerarff Vf Gur Bayl Fva, Naq Vs Lbh Jrer Njner Lbh Jbhyq Xabj.]],
[[Jngre Va Gur Rlrf Naq Nypbuby Va Gur Rlrf Ner Cerggl Zhpu Gur Fnzr V Xabj Guvf Sebz Svefg Unaq Rkcrevrapr.]],
[[Jr Arrq Gb Fgbc Grnpuvat Gur Lbhgu Nobhg Gur Cnfg Naq Rapbhentr Gurz Gb Punatr Gur Shgher]],
[[Jura V Qvr. Gura Lbh Jvyy Ernyvmr]],
[[Jura Gur Svefg Navzny Jrag Rkgvapg Gung Fubhyq'ir Ova N Fvta.]],
[[Jura Lbh Yvir Lbhe Jubyr Yvsr Va N Cevfba Serrqbz Pna Or Fb Qhyy.]],
[[Jul Vf Vg Nyjnlf 3 JUL VF VG NYJNLF 3!!!!!]],
[[Lbh Pna Qvfpbire Rirelguvat Lbh Arrq Gb Xabj Nobhg Rirelguvat Ol Ybbxvat Ng Lbhe Unaqf]],
[[Lbh Zhfg Abg Xabj Snfuvba]],
[[Lbh Gnhtug Zr Ubj Gb Cynl Gur Cvnab Ohg Unir Arire Urneq Zr.]],
[[Lbh Guvax Lbh Trg Vg. LBH QBAG LBH QBAG LBH QBAG!!!!!!!]],
[[Lbh Jbhyq Unir Gb Rng 5 Nccyrf Gbqnl Gb Trg Gur Fnzr Ahgevgvbany Inyhr Nf Na Nccyr Sebz 1950. #Snyybj]],
}

return etc.rot13(pickone(array))
